### ISSUE TITLE
Filament Sensor "lack of filament or filament monitor abnormal"

### ISSUE THREAD

**Issue by localhosthacker** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#45] opened 2020-12-17 16:02 UTC
Hi, I flashed the i3-Mega-S (Mid2020) with new display and the TMCs. Everything works great. But the filmament everytime I want to print this Error occurs: "lack of filament or filament monitor abnormal". But it works with the standard and the david ramiro firmware.
This time i disable the sensor temporarly.

My Board is a TriGorilla v0.0.3. I installed the Marlin-Ai3M-v1.4.6-TMC2208 hex file.

**Comment by Adme84** [comment] 2020-12-26 12:17
Same issues with MEGA_S_DGUS_v1.1.7.hex. I've also disabled my filament sensor to proceed...

**Comment by heizie** [comment] 2021-01-05 18:27
same, i think this is a typical eletrical signal error.
my suggestion is, that we can set a time delay (20 ms), in oder to double check the sensor is closed or not.

**Comment by heizie** [comment] 2021-01-20 11:06
===============update================
it is actually the fault of the filament sensor. (pls read a other closed issue)
either you could use a optical sensor instead of this mechanical switch inside,
or modify the firmware and the sonsor structure, in oder to detect a "close", only when the filament is runout.
that means, sensor closed, and filament runout. no more sensor opened, filament runout

**Comment by knutwurst** [comment] 2021-02-04 07:28
Since this is not a bug in the firmware, but a hardware bug, I close the issue. But in the future I will change the firmware so that the sensor no longer reacts so sensitively.

**Closed by knutwurst** 2021-02-04 07:28 UTC
